// Pure-logic tests for the streak engine, index restore and milestones.
// No browser, no network: `node tests/unit.test.mjs`.
import { computeRun, dayNumber, dayNumbers, dayString, weekStart, FREEZE_MAX } from '../shared/streak.js';
import { parseRootReadme, mergeIntoIndex, entryFromShared } from '../shared/index-restore.js';

const store = {};
globalThis.chrome = {
    storage: {
        local: {
            get: async (keys) => Object.fromEntries([].concat(keys).filter((k) => k in store).map((k) => [k, store[k]])),
            set: async (values) => { Object.assign(store, values); }
        }
    }
};
const { milestonesFor, takeNewMilestones } = await import('../shared/milestones.js');

let failures = 0;
function check(name, ok, detail = '') {
    console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${ok ? '' : `  ${detail}`}`);
    if (!ok) failures += 1;
}

/* ── streaks and freezes ───────────────────────────────────────────── */

const T = dayNumber('2026-10-01');
const set = (...offsets) => new Set(offsets.map((o) => T + o));

let r = computeRun(set(), T);
check('no solves, no run', r.run === 0 && r.freezes === 0 && r.longest === 0);

r = computeRun(set(-2, -1), T);
check('today unfinished does not break a run', r.run === 2 && !r.activeToday);

r = computeRun(set(-3, -2), T);
check('a missed day with no freeze breaks it', r.run === 0 && r.longest === 2, JSON.stringify(r));

r = computeRun(set(-6, -5, -4, -3, -2, -1, 0), T);
check('seven days earn a freeze', r.run === 7 && r.freezes === 1 && r.nextFreezeIn === 7, JSON.stringify(r));

r = computeRun(set(-8, -7, -6, -5, -4, -3, -2, 0), T);
check('a freeze covers a missed day without counting it', r.run === 8 && r.freezes === 0
    && r.frozen.has(T - 1) && r.frozen.size === 1, JSON.stringify({ ...r, frozen: [...r.frozen] }));

r = computeRun(set(-9, -8, -7, -6, -5, -4, -3, 0), T);
check('two misses with one freeze break the run', r.run === 1 && r.longest === 7, JSON.stringify(r));

const long = new Set();
for (let o = -40; o <= 0; o += 1) long.add(T + o);
r = computeRun(long, T);
check(`freezes are capped at ${FREEZE_MAX}`, r.freezes === FREEZE_MAX && r.nextFreezeIn === null, JSON.stringify(r));

check('week starts on Monday', dayString(weekStart(dayNumber('2026-10-01'))) === '2026-09-28'
    && dayString(weekStart(dayNumber('2026-09-28'))) === '2026-09-28'
    && dayString(weekStart(dayNumber('2026-10-04'))) === '2026-09-28');
check('day strings round-trip', dayString(dayNumber('2024-02-29')) === '2024-02-29' && Number.isNaN(dayNumber('nope'))
    && dayNumbers(['2026-10-01', 'junk']).size === 1);

/* ── README restore ────────────────────────────────────────────────── */

const README = `# Algorithm Solutions

> Auto-generated by AlgoPush — organized by platform, then by topic.

## Stats

| Platform | Problems |
| :--- | :--- |
| LeetCode | 2 |
| **Total** | **4** |

---

## AtCoder

- [Other Contests](#atcoder-other-contests) (1)

### AtCoder: Other Contests

| Problem | Difficulty | Solution | Date Solved |
| :--- | :--- | :--- | :--- |
| [A - Welcome](https://atcoder.jp/contests/abc300/tasks/abc300_a) | Gray | [Solution](https://github.com/me/algos/tree/HEAD/AtCoder/Gray/A%20-%20Welcome) | 2026-09-20 |

## Codeforces

### Codeforces: Uncategorized

| Problem | Difficulty | Solution | Date Solved |
| :--- | :--- | :--- | :--- |
| [Odd \\| Even \\[easy\\]](https://codeforces.com/contest/1850/problem/G) | 800 | [Solution](https://github.com/me/algos/tree/HEAD/Codeforces/800/Odd%20Even%20(easy)) | 2026-09-21 |

## LeetCode

### LeetCode: Array

| Problem | Difficulty | Solution | Date Solved |
| :--- | :--- | :--- | :--- |
| [Two Sum](https://leetcode.com/problems/two-sum/) | Easy | [Solution](https://github.com/me/algos/tree/HEAD/LeetCode/Easy/Two%20Sum) | 2026-09-22 |

### LeetCode: Hash Table

| Problem | Difficulty | Solution | Date Solved |
| :--- | :--- | :--- | :--- |
| [Two Sum](https://leetcode.com/problems/two-sum/) | Easy | [Solution](https://github.com/me/algos/tree/HEAD/LeetCode/Easy/Two%20Sum) | 2026-09-22 |
| [Odd Title](not-a-link) | Medium | [Solution](https://github.com/me/algos/tree/HEAD/LeetCode/Medium/Odd%20Title) | 2026-09-23 |
`;

const parsed = parseRootReadme(README);
const keys = Object.keys(parsed).sort();
check('README rows come back under the sync path\'s keys', JSON.stringify(keys) === JSON.stringify([
    'AtCoder:abc300/abc300_a', 'Codeforces:1850-G', 'LeetCode:Odd Title', 'LeetCode:two-sum'
]), JSON.stringify(keys));
const twoSum = parsed['LeetCode:two-sum'];
check('a problem under two topics keeps both, once', twoSum.tags.join() === 'Array,Hash Table'
    && twoSum.date === '2026-09-22' && twoSum.difficulty === 'Easy'
    && twoSum.folderUrl === 'https://github.com/me/algos/tree/HEAD/LeetCode/Easy/Two Sum', JSON.stringify(twoSum));
const cf = parsed['Codeforces:1850-G'];
check('escaped titles and parenthesised folders survive', cf.title === 'Odd | Even [easy]'
    && cf.folderUrl.endsWith('/Odd Even (easy)') && cf.tags.length === 0, JSON.stringify(cf));
check('a junk README restores nothing', Object.keys(parseRootReadme('# My notes\n\n| a | b |')).length === 0);

const index = {
    'LeetCode:two-sum': {
        title: 'Two Sum', platform: 'LeetCode', difficulty: 'Easy', tags: [], link: 'https://leetcode.com/problems/two-sum/',
        folderUrl: 'https://github.com/me/algos/tree/HEAD/LeetCode/Easy/Two Sum', date: '2026-09-25', solvedAt: null,
        solutionPath: 'LeetCode/Easy/Two Sum/solution.py'
    },
    'Codeforces:1850-g-legacy': {
        title: 'Odd | Even [easy]', platform: 'Codeforces', difficulty: '800', tags: ['math'],
        link: 'https://codeforces.com/contest/1850/problem/G',
        folderUrl: 'https://github.com/me/algos/tree/HEAD/Codeforces/800/Odd Even (easy)', date: '2026-09-21'
    }
};
const added = mergeIntoIndex(index, parsed);
check('merge adds only what is missing', added === 2 && Object.keys(index).length === 4, `added=${added}`);
check('merge never overwrites what the index holds', index['LeetCode:two-sum'].date === '2026-09-25'
    && index['LeetCode:two-sum'].solutionPath === 'LeetCode/Easy/Two Sum/solution.py');
check('merge fills fields the index was missing', index['LeetCode:two-sum'].tags.join() === 'Array,Hash Table');
check('a different key for the same folder is not a duplicate', !index['Codeforces:1850-G']);

const fromServer = { 'LeetCode:two-sum': entryFromShared({
    key: 'LeetCode:two-sum', platform: 'LeetCode', title: 'Two Sum', difficulty: 'Easy', link: null,
    solutionUrl: null, solvedOn: '2026-09-22', solvedAt: 1758500000000
}) };
check('shared solves fill a missing live stamp', mergeIntoIndex(index, fromServer) === 0
    && index['LeetCode:two-sum'].solvedAt === 1758500000000);

/* ── milestones ────────────────────────────────────────────────────── */

const many = {};
for (let i = 0; i < 12; i += 1) many[`LeetCode:p${i}`] = { title: `p${i}`, platform: 'LeetCode', date: dayString(T - i) };
const m = milestonesFor(many, T);
check('milestones count solves and runs', m.total === 12 && m.run === 12
    && m.earned.map((e) => e.id).join() === 'solves-10,run-7' && m.next.solves.value === 25 && m.next.run.value === 14,
    JSON.stringify(m));

check('first look records milestones silently', (await takeNewMilestones(many)).length === 0
    && store.milestonesSeen.length === 2);
for (let i = 12; i < 26; i += 1) many[`LeetCode:p${i}`] = { title: `p${i}`, platform: 'LeetCode', date: dayString(T - i) };
const fresh = await takeNewMilestones(many);
check('new milestones come back highest first', fresh.map((f) => f.id).join() === 'solves-25,run-14', JSON.stringify(fresh));
check('each milestone is announced once', (await takeNewMilestones(many)).length === 0);

console.log(failures ? `\n${failures} failing` : '\nall passing');
if (failures) process.exitCode = 1;
